from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
import sys

sys.path.insert(0, r'C:\Users\farma\.codex\plugins\cache\openai-primary-runtime\documents\26.812.11052\skills\documents\scripts')
from table_geometry import apply_table_geometry, column_widths_from_weights

OUT = 'MmaamulPro_V2_Client_User_Manual.docx'

def shade(c, color):
    p=c._tc.get_or_add_tcPr(); e=OxmlElement('w:shd'); e.set(qn('w:fill'),color); p.append(e)
def header_row(row):
    p=row._tr.get_or_add_trPr(); e=OxmlElement('w:tblHeader'); e.set(qn('w:val'),'true'); p.append(e)
def page_num(p):
    r=p.add_run(); e=OxmlElement('w:fldSimple'); e.set(qn('w:instr'),'PAGE'); r._r.append(e)
def cell(c, value, bold=False, color=None):
    c.text=''; p=c.paragraphs[0]; p.paragraph_format.space_after=Pt(0); r=p.add_run(str(value)); r.bold=bold
    if color: r.font.color.rgb=RGBColor.from_string(color)
    c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
def grid(headers, rows, widths=None):
    t=d.add_table(rows=1, cols=len(headers)); t.style='Table Grid'; t.autofit=False; t.alignment=WD_TABLE_ALIGNMENT.CENTER; header_row(t.rows[0])
    for i,x in enumerate(headers):
        cell(t.rows[0].cells[i],x,True,'FFFFFF'); shade(t.rows[0].cells[i],'1F4E79')
        if widths: t.rows[0].cells[i].width=Inches(widths[i])
    for row in rows:
        cs=t.add_row().cells
        for i,x in enumerate(row):
            cell(cs[i],x)
            if widths: cs[i].width=Inches(widths[i])
    apply_table_geometry(t, column_widths_from_weights(widths or [1] * len(headers), 9360))
    d.add_paragraph('')
def note(tag, text, fill='EAF2F8'):
    t=d.add_table(rows=1, cols=1); t.autofit=False; header_row(t.rows[0]); c=t.cell(0,0); shade(c,fill); p=c.paragraphs[0]; p.paragraph_format.space_after=Pt(0); r=p.add_run(tag+'  '); r.bold=True; r.font.color.rgb=RGBColor(31,78,121); p.add_run(text); apply_table_geometry(t, [9360]); d.add_paragraph('')
def h1(s): d.add_heading(s,1)
def h2(s): d.add_heading(s,2)
def h3(s): d.add_heading(s,3)
def para(s): d.add_paragraph(s)
def bullets(xs):
    for x in xs: d.add_paragraph(x,style='List Bullet')
def steps(xs):
    for x in xs: d.add_paragraph(x,style='List Number')
def page(name,purpose,when,how,track,fields=None,related=None,important=None):
    h2(name); para(purpose); h3('When to use it'); para(when); h3('How to use it'); steps(how)
    if fields: h3('Fields, lists and actions'); grid(['Item','What it does'],fields,[2.05,4.25])
    h3('Where to track the result'); para(track)
    if related: h3('Related pages'); para(related)
    if important: note('Important',important,'FFF4E5')

d=Document(); sec=d.sections[0]; sec.top_margin=sec.bottom_margin=Inches(.85); sec.left_margin=sec.right_margin=Inches(.85); sec.header_distance=Inches(.35); sec.footer_distance=Inches(.35)
for n,sz,col,b,a in [('Normal',10.5,'000000',0,5),('Title',30,'1F4E79',0,12),('Heading 1',17,'1F4E79',16,8),('Heading 2',13,'2E74B5',12,5),('Heading 3',11,'1F4E79',8,4)]:
    s=d.styles[n]; s.font.name='Calibri'; s.font.size=Pt(sz); s.font.color.rgb=RGBColor.from_string(col); s.font.bold=n!='Normal'; s.paragraph_format.space_before=Pt(b); s.paragraph_format.space_after=Pt(a); s.paragraph_format.line_spacing=1.1
for n in ['List Bullet','List Number']:
    d.styles[n].font.name='Calibri'; d.styles[n].font.size=Pt(10.5); d.styles[n].paragraph_format.space_after=Pt(3)
hp=sec.header.paragraphs[0]; hp.text='MAAMULPRO V2  |  CLIENT USER MANUAL'; hp.runs[0].font.color.rgb=RGBColor(31,78,121); hp.runs[0].font.bold=True
fp=sec.footer.paragraphs[0]; fp.alignment=WD_ALIGN_PARAGRAPH.RIGHT; fp.add_run('MaamulPro V2 Client User Manual  |  Page '); page_num(fp)

p=d.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.paragraph_format.space_before=Pt(110); r=p.add_run('MaamulPro V2'); r.font.size=Pt(34); r.bold=True; r.font.color.rgb=RGBColor(31,78,121)
p=d.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=p.add_run('Client User Manual'); r.font.size=Pt(24); r.bold=True; r.font.color.rgb=RGBColor(46,116,181)
p=d.add_paragraph('Overview | People & finance | Construction | Real estate | Materials | Administration'); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.runs[0].font.size=Pt(12); p.runs[0].font.color.rgb=RGBColor(89,89,89)
d.add_paragraph(''); note('Edition','Prepared from the current MaamulPro V2 client application source, including its visible navigation labels, forms, actions, permissions and record lifecycles.')
d.add_page_break()
h1('Table of Contents')
grid(['Section'],[(x,) for x in ['1. About this guide','2. Signing in and access','3. Navigation and Overview','4. People & finance','5. Construction','6. Real estate','7. Materials','8. Reports and Administration','9. End-to-end workflows','10. Quick guides and troubleshooting','11. Glossary']],[6.3])
note('Scope','This is a client-company manual. Platform Internal Admin pages (companies, subscriptions and platform administration) are deliberately excluded.')
d.add_page_break()

h1('1. About this guide')
para('MaamulPro V2 is a business-management application with six navigation groups: Overview, People & finance, Construction, Real estate, Materials and Administration. What a person sees depends on the company subscription and the permissions granted to their account.')
grid(['Navigation group','Pages available when enabled and permitted'],[
('Overview','Dashboard; Analytics'),('People & finance','Staff; Financials; Chart of accounts; Journal entries; Financial reports; Payroll; Payslips'),('Construction','Overview; Projects; Tasks; Expenses; Manpower; Inventory; Contracts; Reports'),('Real estate','Overview; Properties; Clients; Deals; Rentals; Tenants; Rent payments; Reports'),('Materials','Overview; Inventory; Suppliers; Purchases; Customers; Sales; Transportation; Reports'),('Administration','Reports; Report schedules; Audit logs; Roles; Settings')],[1.55,4.75])
note('Terminology','This manual uses the labels that users see in the V2 sidebar and page headings. Internal developer names and legacy terminology are not used as client instructions.')

h1('2. Signing in and access')
page('2.1 Sign in','Use the Sign in page to start a session with your company account.','At the start of a work session, or after your password or access has been changed.',['Open Sign in.','Enter your registered email address and password.','Select Sign in. The system opens Overview or the first page available to your account.'],'If a page is unavailable after you sign in, check your assigned role with a company administrator.', [('Forgot password','Starts the password-recovery process.'),('Show/Hide password','Lets you check the password before signing in.'),('Locked / No Access','Explains that the account or requested page is not currently available.')], 'Staff Management; Roles & Permissions; Company & Account Settings.','Do not share credentials. Access changes can require you to sign in again.')
page('2.2 Password recovery and account security','Use password recovery when you cannot use your current password; use Security in Settings when you can sign in and want to change it.','When a password is forgotten, expired, or must be changed.',['Select Forgot password from Sign in and follow the recovery steps sent to the account email.','After signing in, open Administration > Settings > Security to change your password.','Enter the current password and a new password of at least six characters.','After saving a new password, sign in again on this device.'],'Use Settings > Security for a voluntary password change; use the recovery route only when you cannot sign in.', [('Current password','Required for a signed-in password change.'),('New password','Must contain at least six characters.'),('Account status','A company administrator can activate/deactivate a staff login from Staff Management.')], 'Staff Management; Settings.','A deactivated account cannot be used to sign in.')

h1('3. Navigation and Overview')
page('3.1 Sidebar, tables and record actions','The left sidebar is the main way to open sections. Lists use the same practical pattern: search/filter, view records, then use the permitted action buttons.','Whenever you need to find, create, edit or follow up on a record.',['Choose a navigation group, then select the page name.','Use the search box and available filters to narrow the displayed records.','Select Open, View, a linked record name, or a row action to inspect details.','Use Add, New, Edit, Delete, Print, Export CSV or a status button only when it appears for your account.'],'The list or related detail page is the normal place to return to a record.', [('Status badge','Displays the record state. Actions change as the state changes.'),('Search / filters','Limit the list without changing records.'),('New / Add','Creates a record when you have create permission.'),('Edit / Delete','Available only when you have the relevant permission and the record allows it.'),('Print / Export','Creates a printable view or CSV from the displayed page where provided.')], 'Every module.','A hidden button means your account does not have the related permission, or the feature is not included for the company.')
page('3.2 Overview','Overview is the company dashboard. It consolidates financial figures, enabled-module summaries and recent activity.','For a quick current picture before opening a detailed module.',['Open Overview > Dashboard.','Review income, expense, net result, staff and transaction indicators.','Use the financial performance chart to switch between 7, 30 and 90 days.','Open the linked Construction, Real estate or Materials cards to investigate the corresponding records.','Use Recent activity to understand recent data changes.'],'Use the linked module pages, Financials, reports or Audit logs for the supporting records.', [('Financial performance','Shows income and net profit over the selected period.'),('Module distribution','Shows record counts for enabled sections.'),('Module summaries','Show Construction, Real estate and Materials indicators when those sections are enabled.'),('Recent activity','Lists recorded user activity.')], 'Financials; Construction; Real estate; Materials; Audit logs.')
page('3.3 Analytics Center','Analytics Center compares income, expense and operational distribution across the selections available to your account.','When a manager needs to compare a period or section without editing records.',['Open Overview > Analytics.','Select All, Construction, Real estate or Materials when the option is shown.','Select 7 days, This month or This year.','Review Income and expenses and Operational distribution.','Open the relevant module/report for detailed records.'],'Analytics is summary-only; use the underlying module pages and reports for record-level follow-up.', [('Section selector','Limits analytics to the selected area.'),('Period selector','Sets weekly, monthly or yearly period.'),('Income and expenses','Shows the financial movement for the selection.'),('Operational distribution','Shows the selected operational distribution.')], 'Overview; Financials; all module Reports.')

h1('4. People & finance')
page('4.1 Staff Management','Staff Management holds employee details, construction assignment, workforce status and the user account attached to a staff member.','Before assigning a person to a project/task, payroll, worker ledger or workforce contract; also when managing login access.',['Open People & finance > Staff and choose Add staff member.','Enter first and last name; then complete phone, position, department, status, salary, hire date and notes.','For Construction staff, select an Assigned project when needed.','Optionally select Create a login account now, then enter email, role and temporary password.','Save the staff member. Select the person later to view details, account controls and recent activity.'],'Use the Staff list for filtering by department/status. Use the selected staff detail for account activation, email/role change and password reset.', [('Required fields','First name and Last name.'),('Department','General, Construction, Real estate or Material management.'),('Staff status','Active, Inactive, On Leave or Terminated.'),('Create a login account now','Adds account email, role and temporary password during creation.'),('Account controls','Activate/Deactivate, Change email, Change role and Reset password.')], 'Projects; Tasks; Manpower; Contracts; Payroll; Roles & Permissions.','Changing a role requires the affected user to sign in again. The current user cannot delete their own account.')
page('4.2 Financials','Financials is the unified list for company income, expenses and synchronised operational entries.','To add a direct company transaction or review transactions created by deals, rent payments, purchases, sales, transportation, construction costs or payroll.',['Open People & finance > Financials.','Use search, type, status and date filters to find records.','Select New transaction for a direct entry. Choose Type, Status, Description, Amount, Date, Category and optional Project or Property source.','Save, then return to the list to edit/delete when permitted.','Use Export CSV when you need the filtered list outside the system.'],'Financials is the main follow-up page; a cleared record may also be reflected in Journal Entries and Financial Reports.', [('Type','Income or Expense.'),('Status','Pending, Processing, Cleared or Cancelled.'),('Category','Reusable financial classification; optional.'),('Source Module','General / Unassigned, Construction Project or Real Estate Property when access allows.'),('Reference','System-friendly transaction reference shown in the list.')], 'Financial Categories; Chart of Accounts; Journal Entries; Financial Reports.','Operational processes may create synchronised records automatically. Do not duplicate those by manually entering the same income/expense.')
page('4.3 Financial Categories','Financial Categories are reusable classifications for direct income and expense entries.','When a useful category is missing from the Financials transaction form.',['Open Settings > Categories, then Manage categories.','Select Add new.','Enter Name, optional Code, Color and Description.','Save, then choose the category from the Financials transaction form.'],'Return to Financial Categories to edit or delete unused categories.', [('Name','Required category name.'),('Code','Optional short reference.'),('Color','Optional visual identifier.'),('Description','Optional explanation of intended use.')], 'Financials.','A category in use by active transactions cannot be deleted.')
page('4.4 Chart of Accounts','Chart of Accounts contains the hierarchical accounts used for double-entry postings and financial reports.','When an authorised finance user needs to maintain the account structure or inspect an account ledger.',['Open People & finance > Chart of accounts.','Use search/type filters and Show inactive to locate an account.','Select Add account; choose account Type, Account name, optional Parent account and Description.','Save. Select Ledger or the account row to view account activity.','Use Edit, Deactivate/Activate or Delete only when permitted.'],'Use the account detail ledger for transactions; use Journal Entries and Financial Reports for wider review.', [('Account Type','Income, Expense, Asset, Liability or Equity.'),('Parent account','Optional parent of the same type.'),('Ledger','Opens transactions posted to the account.'),('Active status','Controls whether an account is available for future use.')], 'Financials; Journal Entries; Account mappings; Financial Reports.','Accounts already used by journal entries, child accounts or payroll cannot be removed.')
page('4.5 Journal Entries','Journal Entries displays every balanced, posted double-entry batch from direct and synchronised transactions.','To inspect accounting evidence, filter batches, or reverse an authorised posted batch.',['Open People & finance > Journal entries.','Search by batch number, memo or reference; filter by status/date as needed.','Open a batch to view debit and credit lines.','Use Reverse where it is available and permitted, then confirm the reversal.'],'Track the original and reversal batches in Journal Entries; account effects appear in Chart of Accounts and Financial Reports.', [('Batch #','Unique journal batch number.'),('Source / Memo / Posted by','Identifies why and by whom the batch was posted.'),('Debit and Credit lines','Show the balanced accounting entries.'),('Reverse','Creates an audit-preserving reversal; it does not alter the original posted batch.')], 'Financials; Chart of Accounts; Financial Reports.','Only a posted batch can be reversed. A batch must remain balanced.')
page('4.6 Financial Reports','Financial Reports runs statement-style accounting views from the posted ledger.','For account balances, income/expense performance or a selected account report.',['Open People & finance > Financial reports.','Choose the report tab.','Set As of date or From/To dates; for account activity, optionally search/select accounts.','Select Run.','Review totals and use Print where provided.'],'Return to the same report to change dates or filters; open Chart of Accounts or Journal Entries for supporting entries.', [('As of date','Used for point-in-time reports.'),('From / To','Used for period reports.'),('Account filter','Limits account activity to selected accounts.'),('Run','Refreshes the report with the selected criteria.')], 'Chart of Accounts; Journal Entries; Financials.')
page('4.7 Payroll and Payslips','Payroll creates a monthly payroll run from eligible staff; Payslips shows employee-level results and printable payslips.','At payroll preparation, approval and payment time, and when an employee needs a payslip.',['Open Payroll and select New payroll.','Enter Payroll name, Year, Month, Pay period, Payment date and optional Expense account.','Add employee lines; selecting an employee fills available staff information. Enter Base salary, Bonuses, Deductions and Tax.','Save as Draft, then use Submit.','An authorised person selects Approve or Reject. After approval, an authorised payer selects Pay.','Open Payslips to search, view and print each resulting employee document.'],'Payroll list tracks the run status; Payslips tracks individual amounts; Financials/Journal Entries show the paid accounting impact.', [('Payroll status','Draft, Pending Approval, Approved, Rejected or Paid.'),('Submit','Moves Draft/Rejected payroll for review.'),('Approve / Pay','Require dedicated approval/payment permissions.'),('Reopen','Returns an eligible pending/approved/rejected run for correction.'),('Payslip','Shows base salary, bonuses, gross, deductions, tax and net salary.')], 'Staff Management; Chart of Accounts; Financials; Journal Entries; Reports.','Only Draft and Rejected payroll runs can be edited. A year/month payroll period cannot be duplicated.')

h1('5. Construction')
page('5.1 Construction overview and Projects','Construction overview summarises active projects, budgets, recorded costs and task completion. Projects holds each site record and its detail page.','To create a site, monitor delivery or open project-linked work.',['Open Construction > Overview for current indicators, or Projects for the full project list.','Select New project and enter Project name, Location, Budget, Progress %, Status, Start/End date, image and Description.','Open a project to view linked Project tasks, Assigned staff, Operational expenses and Workforce contracts.','Use Edit to update the project where permitted.'],'Projects list, project detail and Project progress show the current delivery state; reports provide financial detail.', [('Project status','Planning, Ongoing, On Hold, Completed or Cancelled.'),('Progress %','0–100 percentage displayed on project cards/progress page.'),('Budget','Required project budget.'),('Project detail','Shows related tasks, staff, expenses and contracts.')], 'Tasks; Expenses; Manpower; Inventory; Contracts; Construction Reports.','Deleting a project removes its tasks; existing expenses remain in financial history.')
page('5.2 Project Tasks and Project progress','Project Tasks creates and manages work items; Project progress gives a consolidated view of project and task health.','To assign work, set deadlines, flag blocked work or review completion.',['Open Construction > Tasks and choose Add new.','Select Project, enter Task title, Status, Priority, Progress %, Due date, Assigned staff member and Description.','Save, then update the task as work progresses.','Open Project progress to review overall completion, blocked tasks and deadlines.'],'Tasks list and Project progress are the main follow-up pages; project detail also lists tasks.', [('Task status','Not Started, In Progress, Completed or Blocked.'),('Priority','Low, Medium, High or Urgent.'),('Assigned staff member','Links the task to a Staff record.'),('Due date','Shown in project progress and task health views.')], 'Projects; Staff Management.','Keep task Status and Progress % aligned so delivery reporting remains reliable.')
page('5.3 Operational Expenses, Manpower and Worker Ledger','Operational Expenses records site costs; Manpower dashboard reviews workers and labour costs; Worker Ledger records individual/general labour income or expense activity.','When logging a site expense, checking assigned labour, or recording labour ledger entries.',['For a site cost, open Expenses > Add new and enter Amount, Description, Category, Date and optional Project/Staff member.','Use Manpower to filter the dashboard by project and review Workforce, Latest expenses and Worker ledger.','For a ledger entry, open Worker Ledger > Add new, choose Income/Expense, Amount, Description, Date and optional Project/Staff member.'],'Expenses list, Worker Ledger and Manpower dashboard provide operational follow-up; Financials holds synchronised financial records.', [('Expense categories','Labor, Materials, Equipment, Transport, Utilities, Food or Other.'),('Worker Types','Reusable workforce classifications with Name, Color and Description.'),('Worker Ledger Type','Income or Expense.'),('Project filter','Limits Manpower dashboard to one project.')], 'Staff Management; Projects; Financials; Construction Reports.','Link the relevant project and staff member whenever known; this improves cost and labour traceability.')
page('5.4 Construction inventory','Construction inventory records stock movements for construction activity and can link usage to a project.','When stock is restocked, used, adjusted or transferred for construction.',['Open Construction > Inventory and select Record movement.','Choose a material from the catalog, movement type, quantity, date and project where applicable.','Save the movement.','Review movement history and inventory information; open the material catalog only if you have materials-product access.'],'Construction inventory list and Construction Reports; materials themselves are managed from Materials > Inventory.', [('Movement types','Restock, Usage, Adjustment or Transfer.'),('Material','Selected from the material catalog.'),('Project','Use for site usage so the movement is tied to the correct project.'),('Quantity / date','Defines the stock movement.')], 'Materials > Inventory; Projects; Construction Reports.','Record actual stock movements only. Use a correction movement rather than entering a duplicate record.')
page('5.5 Workforce Contracts','Contracts manages a project labour contract, its assigned workers, budget adjustments and payments.','When a project has a defined workforce budget that must be controlled separately.',['Open Construction > Contracts and create a contract for a project.','Enter title, description, original budget, dates and notes; assign workers.','Move the contract through the available status actions.','For an active/completed contract, record worker payments and authorised budget adjustments.','Review total paid, remaining budget, workers and payment history in the contract detail.'],'Contracts page and project detail; payments also create linked financial records.', [('Contract status','Draft, Active, Completed, Cancelled or Suspended.'),('Original budget','Starting contract budget.'),('Assigned workers','Staff linked to the contract.'),('Payment','Requires an assigned worker and cannot exceed remaining budget.'),('Adjustment','Records an authorised budget change with reason.')], 'Projects; Staff Management; Manpower; Financials; Construction Reports.','Payments require the specific contract-payment permission; do not pay a Draft, Suspended or Cancelled contract.')

h1('6. Real estate')
page('6.1 Portfolio overview and Properties','Portfolio overview gives property, client, sales, rental and collection indicators. Properties maintains the property portfolio and record detail.','To add a property, check availability or follow property-linked business activity.',['Open Real estate > Properties and select Add property.','Enter Title, Type, Status, Price, Area, Bedrooms, Bathrooms, Address, image and Description.','Save, then select View property to review details.','Use Edit only when you need to update the listing.'],'Properties list and property detail. The detail shows Property deals, Rental contracts, Tenants and Financial transactions.', [('Property Type','House, Apartment, Land or Commercial.'),('Property Status','Available, Sold, Rented or Under Contract.'),('Property image','Optional uploaded image.'),('Price','Required property price.')], 'Clients; Deals; Rentals; Rent payments; Financials; Real estate Reports.','A property with active contracts or deals cannot be deleted. Status is also maintained by deal/rental activity.')
page('6.2 Clients, Property Deals and Property sales','Clients stores buyer/seller/investor contacts. Property Deals creates sale or rental settlements. Property sales is the sale-only tracking view.','When opening a new sale/rental settlement or following collections.',['Create the client first: Name is required; Email, Phone and Notes are optional.','Open Deals > Add new, choose Property and Client, then select Sale or Rental.','Enter Payment status, Total amount, Paid amount, Closed date and Notes.','Save; open Property sales to review sale-only totals, collected money and outstanding balance.','Update the deal as payments change.'],'Deal detail, client detail and property detail show linked records; Financials shows synchronised financial entries.', [('Deal Type','Sale or Rental.'),('Payment status','Paid, Partial, Pending, Overdue or Refunded.'),('Total / Paid amount','Used to calculate the outstanding balance.'),('Closed date','The close/settlement date.')], 'Properties; Clients; Financials; Real estate Reports.','A new deal cannot claim a property that is already Sold or Rented. A paid sale drives the property to Sold; an unpaid sale is Under Contract.')
page('6.3 Rentals, Tenants, Rental Contracts and Rent Payments','Rentals is the operational lease hub. It brings together tenants, leases, scheduled payment obligations and collections.','To create a lease, generate monthly rent invoices, track a payment or follow late/unpaid items.',['Create a tenant with Name, Email, Phone, National ID / Passport and Notes.','From Rentals select New lease. Choose Tenant and Property, then enter Monthly rent, Start/End dates, Renewal date, Status and Notes.','Use Generate monthly invoices to create missing monthly payment obligations for active leases.','Open Rent payments > Add new. Select the Rental contract when known, then verify Tenant, Due/Paid dates, Amount due/paid, Status, Receipt number and Notes.','Use Mark paid, Mark partial or Mark late to update an existing payment.'],'Rentals shows lease register and payment obligations; property detail and real-estate reports provide additional follow-up.', [('Lease status','Active, Expired, Renewal Due or Terminated.'),('Payment status','Paid, Unpaid, Late or Partial.'),('Generate monthly invoices','Creates missing monthly rent payment records for active leases.'),('Receipt number','Reference for a rent payment.'),('Monthly contracted','Total monthly rent across active leases.')], 'Properties; Tenants; Rental Contracts; Rent Payments; Financials; Real estate Reports.','The system derives payment status from amount due, amount paid and due date. A property cannot have more than one active/renewal-due rental contract.')

h1('7. Materials')
page('7.1 Materials overview and Stock catalog','Materials overview monitors products, stock value, low-stock exposure, purchase orders, sales and delivery tracking. Stock catalog is the product/stock list.','To monitor inventory or add/manage a stocked material.',['Open Materials > Overview for summary indicators.','Open Materials > Inventory (Stock catalog) and use search/warehouse filter to locate a material.','Select Add product to create a material, or All products to manage the wider catalog.','Use Edit/Delete only when permitted.'],'Stock catalog shows on-hand quantity, pricing, stock value and status. Materials Reports provides movement/purchase/sale analysis.', [('Material fields','Material name, Unit, Unit cost, Opening stock quantity, Low stock alert threshold, Warehouse, Category and Product image.'),('Unit','Bag, KG, Piece, Meter, Liter or Ton.'),('Low stock','Shown when on-hand quantity is at/below the threshold.'),('Stock value','Quantity multiplied by unit cost.')], 'Purchases; Sales; Transportation; Construction inventory; Materials Reports.','Create products before using them in purchase orders, sales invoices, delivery records or construction movements.')
page('7.2 Suppliers and Purchase Orders','Suppliers maintains procurement contacts and balances. Purchase Orders manages the order-to-receipt lifecycle.','When buying stock from a supplier.',['Create a supplier with Name, Email, Phone, Address, Opening balance and Notes.','Create a Purchase Order: enter Order number, Supplier, Status, Ordered/Received date and Purchase items.','Each purchase item requires a material, Quantity and Unit cost. Save the draft.','Select Mark ordered when the order is placed. When stock is physically received, select Receive stock.','Use Cancel for an order that will not proceed; Reopen draft is available for a cancelled order that must be revised.'],'Purchase Orders tracks the status; Stock catalog shows received quantity/cost effect; Financials tracks the linked financial result.', [('Purchase status','Draft, Ordered, Received or Cancelled.'),('Receive stock','Updates received stock and weighted cost.'),('Purchase items','Material, Quantity and Unit cost.'),('Supplier balance','Tracked on the supplier record.')], 'Stock catalog; Suppliers; Financials; Materials Reports.','Receive stock only after confirming the actual delivery. Do not use a second purchase order to correct a received order without checking its stock effect.')
page('7.3 Customers and Material Sales','Customers maintains sales accounts. Material Sales issues a material invoice and records its stock/revenue/receivable effect.','When selling material to a customer.',['Create a customer with Name, Email, Phone, Address and Balance.','Create a sales invoice: enter Invoice number, Customer, Paid amount, Discount %, Invoice date, Invoice items and Notes.','For each invoice item choose a material, Quantity and Unit price.','Save and use the page print action when a customer invoice is needed.'],'Material Sales list, customer record, Stock catalog, Financials and Materials Reports.', [('Invoice number','Required sales reference.'),('Paid amount','Amount collected for the invoice.'),('Discount %','Invoice-level discount.'),('Invoice items','Material, Quantity and Unit price.'),('Print','Creates a printable invoice view.')], 'Stock catalog; Customers; Financials; Materials Reports.','Sales use the selected material stock. Check the product, quantity, price and discount before saving.')
page('7.4 Transportation','Transportation records delivery dispatch and completion for a material movement.','When material is being delivered and delivery cost must be tracked.',['Open Materials > Transportation and select New delivery record.','Enter Delivery number, Responsible person, Material, Quantity, Cost, Status, Delivery date and Notes.','Save as Pending, then select Start transit at dispatch.','Select Mark delivered only after completion is confirmed.','Use Cancel when delivery will not proceed.'],'Transportation list and Materials overview track delivery state; delivered records post their expense to Financials.', [('Delivery status','Pending, In Transit, Delivered or Cancelled.'),('Responsible person','Required person responsible for delivery.'),('Cost','Required delivery cost.'),('Mark delivered','Completes delivery and posts the related expense.')], 'Stock catalog; Purchases; Sales; Financials; Materials Reports.','Do not mark a delivery Delivered prematurely, because the action has a financial posting effect.')

h1('8. Reports and Administration')
page('8.1 Reports','Reports pages provide detailed financial and operational analysis. Core reports run company-wide financial/payroll reports; Construction, Real estate and Materials reports begin by choosing the project, property or material, then allow category and item detail.','When management needs a printable, date-filtered view or needs to trace a summary to a source item.',['Open the relevant Reports page from its navigation group.','For a core report, select the report card and optional date range, then Run.','For a module report, select the project/property/material, choose a report category, and open a listed item for full details.','Use Clear dates, Back navigation and Print/Print summary/Print voucher as provided.'],'The same Reports page retains the drill-down path; use the original record page for edits.', [('Core reports','Financial and Payroll reports with optional dates.'),('Construction reports','Project delivery/cost detail.'),('Real estate reports','Property rent, sales and lease detail.'),('Materials reports','Material movement, received purchases and sales detail.'),('Print','Available on applicable summary/detail pages.')], 'Financial Reports; all operational modules.')
page('8.2 Report schedules','Report schedules creates controlled weekly, monthly or yearly email delivery of an available report.','When a report must be sent regularly to named recipients.',['Open Administration > Report schedules and select New schedule.','Choose Report and enter Schedule name, Frequency and Next run date.','Enter comma-separated Email recipients.','Optionally set report Start/End date and Project / property / material scope.','Save; use Edit or Delete later as needed.'],'The Report schedules list shows report, frequency, recipients, next run and active/inactive state.', [('Frequency','Weekly, Monthly or Yearly.'),('Email recipients','Comma-separated email addresses.'),('Scope','Optional project/property/material constraint.'),('Next run','The next scheduled delivery date.')], 'Reports.','Check recipient addresses and scope before saving. Scheduling access is restricted to report administrators.')
page('8.3 Roles & Permissions','Roles & Permissions manages custom role definitions and staff account access.','When a company administrator must grant, reduce or review system access.',['Open Administration > Roles.','On Roles, create a role with Role key, Name, Description and selected permissions, or search/view/edit an existing role.','On Users, choose a staff account with a login.','Assign active roles and/or apply a direct Allow/Deny permission override with an optional reason.','Ask the affected user to sign in again.'],'Roles list shows assigned-user counts; selected user access shows role and direct override information.', [('Role key','Unique uppercase-style role identifier; cannot be changed after creation.'),('Permissions','Selected by grouped permission list.'),('Direct override','Explicit Allow or Deny for one user.'),('System role','A staff account’s baseline role.'),('Delete role','Not available for system roles.')], 'Staff Management; Settings.','Roles and direct permissions immediately affect access after a new sign-in. Use direct overrides only when a role is not the right long-term solution.')
page('8.4 Audit Logs and Company & Account Settings','Audit Logs records authorised company activity. Settings contains company controls, personal account/security controls, preferences, financial categories/account mappings and subscription visibility.','When checking change history or maintaining company/account configuration.',['Open Audit logs to search/filter activity and inspect who changed data.','Open Settings. Company owners can use Company, Categories, Account mappings and Subscription.','All signed-in users can use My account, Security and Preferences.','Save profile/company changes from the relevant section.'],'Audit Logs retains history. Settings pages retain the current company/profile configuration.', [('My account','Profile photo, name, email and English/Somali language.'),('Security','Current password and new password.'),('Preferences','Account/security emails, scheduled report notifications and compact tables; stored in the current browser.'),('Company','Company logo, name, email, phone, address and description.'),('Account mappings','Links automated financial processes to chart-of-account entries.'),('Subscription','Shows included features and capacity usage.')], 'Staff Management; Financials; Chart of Accounts; Reports.','Audit-log deletion and owner-only settings are permission-controlled. Preferences are browser-specific, not company-wide.')

h1('9. End-to-end workflows')
grid(['Workflow','Start → process → result → track'],[
('Payroll','Staff active → Payroll creates employee lines → Submit → authorised Approve → authorised Pay → Payslips, Financials and Journal Entries.'),('Construction delivery','Project → Tasks/Staff → Expenses, Worker Ledger, Inventory movements and Workforce Contracts → Project progress → Construction Reports/Financials.'),('Property sale','Property + Client → Property Deal (Sale) → payment amounts/status updated → Property sales + deal/property detail + Financials.'),('Rental collection','Tenant + Property → Rental Contract → Generate monthly invoices or create Rent Payment → Mark Paid/Partial/Late → Rentals, property detail, Financials and Reports.'),('Material procurement','Material product + Supplier → Purchase Order Draft → Mark ordered → Receive stock → Stock catalog, supplier balance, Financials and Materials Reports.'),('Material sale/delivery','Customer + Sales Invoice → material quantity/price/discount → stock/revenue update → Transportation Pending/In Transit/Delivered where used → Financials and Materials Reports.')],[1.45,4.85])

h1('10. Quick guides and troubleshooting')
grid(['Need','Use this path'],[
('Add a staff login','Staff > open staff member > Create login account, or select Create a login account now during staff creation.'),('Record a company cost','People & finance > Financials > New transaction > Expense > details/category/source > Save.'),('Correct a posted accounting item','Open Journal Entries and use the permitted Reverse action; do not edit the original posted batch.'),('Create a construction task','Construction > Tasks > Add new > Project + Task title + status/priority/due date/assignment > Save.'),('Record stock receipt','Materials > Purchases > select order > Receive stock after physical verification.'),('Create a lease','Real estate > Rentals > New lease > tenant/property/rent/dates/status > Save.'),('Collect rent','Real estate > Rent payments > add/select contract + amounts/dates > Save or Mark paid/partial/late.'),('Issue material invoice','Materials > Sales > add new > customer + items + paid/discount/date > Save/Print.'),('Missing menu/action','Ask an administrator to check the company subscription/section visibility and your Roles & Permissions.'),('Cannot pay payroll','Confirm it is Approved and that the user has payroll payment permission.'),('Cannot delete a record','It may have dependent activity or your account may lack delete permission; review the page message and linked records.')],[2.0,4.3])

h1('11. Glossary')
grid(['Term','Meaning'],[
('Chart of Accounts','The finance account structure used for journal posting and reports.'),('Cleared','A financial transaction state used for completed/posted-ready entries.'),('Deal','A recorded Property Sale or Rental settlement between a property and client.'),('Lease','A Rental Contract linking tenant, property, rent and dates.'),('Paid / Partial / Unpaid / Late','Rent payment states based on due/paid amount and due date.'),('Payroll run','A month/year payroll record containing employee salary calculations.'),('Property deal status','Paid, Partial, Pending, Overdue or Refunded settlement state.'),('Purchase Order','A material order that moves Draft → Ordered → Received, or is Cancelled.'),('Status badge','The visible label showing a record’s current state.'),('Stock catalog','The Materials inventory page listing products, stock and thresholds.'),('Workforce Contract','A project labour contract with budget, assigned workers, adjustments and payments.')],[1.8,4.8])
note('Coverage confirmation','This manual covers the current V2 client navigation, every client page/route, current input fields, visible actions, current statuses, permission restrictions and cross-page workflows. Internal platform administration is intentionally outside client scope.')
d.save(OUT)
print(OUT)
