import { ReactNode } from 'react';
import DotLoader from './DotLoader';

export const humanize = (value: string) => value.replace(/[_-]/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/\b\w/g, (letter) => letter.toUpperCase());
export const money = (value: unknown, currency = 'USD') => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(value || 0));
export const shortDate = (value: unknown) => value ? new Intl.DateTimeFormat(undefined, { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(String(value))) : '—';
export const StatusPill = ({ value }: { value?: string | null }) => { const normalized = String(value || 'UNKNOWN').toUpperCase(); const positive = ['ACTIVE', 'PAID', 'CLEARED', 'COMPLETED', 'APPROVED', 'DELIVERED', 'RECEIVED', 'AVAILABLE']; const negative = ['INACTIVE', 'CANCELLED', 'REJECTED', 'TERMINATED', 'EXPIRED', 'OVERDUE', 'SUSPENDED']; const tone = positive.includes(normalized) ? 'success' : negative.includes(normalized) ? 'danger' : 'warning'; return <span className={`badge bg-${tone}-light text-${tone}`}>{humanize(normalized)}</span>; };
export const PageHeader = ({ title, description, actions, eyebrow }: { title: string; description?: string; actions?: ReactNode; eyebrow?: string }) => <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div>{eyebrow && <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">{eyebrow}</p>}<h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">{title}</h1>{description && <p className="mt-1 max-w-3xl text-white-dark">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
export const StatGrid = ({ items }: { items: { label: string; value: ReactNode; hint?: string; tone?: string }[] }) => <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <div className="panel" key={item.label}><p className="text-xs font-bold uppercase tracking-wider text-white-dark">{item.label}</p><p className={`mt-2 text-2xl font-black text-${item.tone || 'primary'}`}>{item.value}</p>{item.hint && <p className="mt-1 text-xs text-white-dark">{item.hint}</p>}</div>)}</div>;
export const EmptyState = ({ title = 'No records found', description, action }: { title?: string; description?: string; action?: ReactNode }) => <div className="p-10 text-center"><div className="mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full bg-primary-light text-xl text-primary">○</div><h3 className="font-bold">{title}</h3>{description && <p className="mx-auto mt-1 max-w-md text-sm text-white-dark">{description}</p>}{action && <div className="mt-4 flex justify-center">{action}</div>}</div>;
export const LoadingState = ({ label = 'Loading live data…' }: { label?: string }) => <div className="flex min-h-44 flex-col items-center justify-center gap-4 p-10 text-center text-white-dark"><DotLoader label={label} /><span className="text-sm">{label}</span></div>;
export const ErrorAlert = ({ message, onRetry }: { message: string; onRetry?: () => void }) => <div className="mb-5 flex items-center justify-between gap-4 rounded-md bg-danger-light p-4 text-danger" role="alert"><span>{message}</span>{onRetry && <button className="btn btn-sm btn-outline-danger" onClick={onRetry}>Retry</button>}</div>;
export const Modal = ({ title, open, onClose, children, wide = false }: { title: string; open: boolean; onClose: () => void; children: ReactNode; wide?: boolean }) => !open ? null : <div className="fixed inset-0 z-[110] grid place-items-center bg-black/60 p-4" onMouseDown={(event) => event.currentTarget === event.target && onClose()}><div className={`panel max-h-[92vh] w-full overflow-y-auto ${wide ? 'max-w-5xl' : 'max-w-2xl'}`}><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button className="btn btn-sm btn-outline-dark" onClick={onClose}>Close</button></div>{children}</div></div>;
export const Field = ({ label, required, children, hint }: { label: string; required?: boolean; children: ReactNode; hint?: string }) => <label className="block"><span className="font-semibold">{label}{required && <span className="text-danger"> *</span>}</span>{children}{hint && <span className="mt-1 block text-xs text-white-dark">{hint}</span>}</label>;
