import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import ReactApexChart from 'react-apexcharts';
import AppShell from '../components/maamulpro/AppShell';
import { api } from '../lib/api';
import { EmptyState, ErrorAlert, LoadingState, PageHeader, StatGrid, StatusPill, humanize, money, shortDate } from '../components/maamulpro/PageKit';
import { IRootState } from '../store';

type Trend = { label: string; value: number };
type PlatformMetrics = {
    totalCompanies: number; activeCompanies: number; expiredCompanies: number; trialCompanies: number; totalUsers: number; activeSubscriptions: number; monthlyRevenue: number;
    outstandingInvoices: { count: number; amount: number };
    latestRegistrations: { id: string; name: string; subdomain: string; status: string; subscriptionStatus: string; createdAt: string }[];
    recentTransactions: { id: string; transactionType: string; newStatus: string; amount?: number; createdAt: string; company: { id: string; name: string } }[];
    subscriptionStatusDistribution: { status: string; count: number }[]; growthTrend: Trend[]; revenueTrend: Trend[]; systemHealth: { database: string; expiringSoon: number };
};

const VristoTrendChart = ({ title, data, type, currency = false }: { title: string; data: Trend[]; type: 'area' | 'bar'; currency?: boolean }) => {
    const isDark = useSelector((state: IRootState) => state.themeConfig.theme === 'dark' || state.themeConfig.isDarkMode);
    const options: any = { chart: { type, fontFamily: 'Nunito, sans-serif', toolbar: { show: false }, zoom: { enabled: false } }, colors: [currency ? '#00ab55' : '#4361ee'], dataLabels: { enabled: false }, stroke: { curve: 'smooth', width: type === 'area' ? 2 : 0 }, fill: type === 'area' ? { type: 'gradient', gradient: { opacityFrom: .35, opacityTo: .05, stops: [45, 100] } } : { opacity: 1 }, plotOptions: { bar: { borderRadius: 4, columnWidth: '45%' } }, grid: { borderColor: isDark ? '#191e3a' : '#e0e6ed', strokeDashArray: 5 }, xaxis: { categories: data.map((row) => row.label), axisBorder: { show: false }, axisTicks: { show: false }, labels: { style: { colors: '#888ea8' } } }, yaxis: { labels: { formatter: (value: number) => currency ? `$${Math.round(value).toLocaleString()}` : Math.round(value).toLocaleString(), style: { colors: '#888ea8' } } }, tooltip: { y: { formatter: (value: number) => currency ? money(value) : value.toLocaleString() } }, theme: { mode: isDark ? 'dark' : 'light' } };
    return <div className="panel h-full"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-bold">{title}</h2><p className="text-sm text-white-dark">Last six months</p></div><span className={`badge ${currency ? 'bg-success-light text-success' : 'bg-primary-light text-primary'}`}>{currency ? money(data.reduce((sum, row) => sum + row.value, 0)) : `${data.reduce((sum, row) => sum + row.value, 0)} total`}</span></div>{data.some((row) => row.value) ? <ReactApexChart options={options} series={[{ name: title, data: data.map((row) => row.value) }]} type={type} height={285} className="overflow-hidden" /> : <EmptyState title="No activity in this period" description="Live data will appear as platform activity is recorded." />}</div>;
};

const VristoStatusChart = ({ data }: { data: PlatformMetrics['subscriptionStatusDistribution'] }) => {
    const isDark = useSelector((state: IRootState) => state.themeConfig.theme === 'dark' || state.themeConfig.isDarkMode);
    const options: any = { chart: { type: 'donut', fontFamily: 'Nunito, sans-serif' }, labels: data.map((row) => humanize(row.status)), colors: data.map((row) => row.status === 'ACTIVE' ? '#00ab55' : row.status === 'EXPIRED' ? '#e7515a' : row.status === 'SUSPENDED' ? '#805dca' : '#e2a03f'), dataLabels: { enabled: false }, stroke: { show: true, width: 6, colors: [isDark ? '#0e1726' : '#fff'] }, legend: { position: 'bottom', labels: { colors: isDark ? '#bfc9d4' : '#0e1726' } }, plotOptions: { pie: { donut: { size: '68%', labels: { show: true, total: { show: true, label: 'Companies', color: '#888ea8', formatter: (context: any) => context.globals.seriesTotals.reduce((sum: number, value: number) => sum + value, 0) } } } } }, theme: { mode: isDark ? 'dark' : 'light' } };
    return <div className="panel h-full"><h2 className="text-lg font-bold">Subscription status</h2><p className="mb-2 text-sm text-white-dark">Current company distribution</p>{data.length && data.some((row) => row.count) ? <ReactApexChart options={options} series={data.map((row) => row.count)} type="donut" height={300} className="overflow-hidden" /> : <EmptyState title="No subscriptions yet" description="Distribution will appear after the first subscription is assigned." />}</div>;
};

const PlatformDashboard = () => {
    const [metrics, setMetrics] = useState<PlatformMetrics | null>(null);
    const [error, setError] = useState('');
    const load = () => { setError(''); api<PlatformMetrics>('/api/superadmin/metrics').then(setMetrics).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load platform metrics')); };
    useEffect(() => { load(); }, []);
    return <AppShell><PageHeader eyebrow="Platform administration" title="Platform dashboard" description="Live platform performance, subscription exposure, and administrative activity." actions={<><Link className="btn btn-outline-primary" to="/superadmin/billing">Review billing</Link><Link className="btn btn-primary" to="/superadmin/companies/new">Onboard company</Link></>} />
        {error && <ErrorAlert message={error} onRetry={load} />}
        {!metrics ? <div className="panel"><LoadingState label="Loading platform data…" /></div> : <>
            <StatGrid items={[{ label: 'Total companies', value: metrics.totalCompanies }, { label: 'Active companies', value: metrics.activeCompanies, tone: 'success' }, { label: 'Expired companies', value: metrics.expiredCompanies, tone: 'danger' }, { label: 'Trial companies', value: metrics.trialCompanies, tone: 'warning' }, { label: 'Total active users', value: metrics.totalUsers, tone: 'info' }, { label: 'Active subscriptions', value: metrics.activeSubscriptions, tone: 'success' }, { label: 'Monthly revenue', value: money(metrics.monthlyRevenue), tone: 'primary' }, { label: 'Outstanding invoices', value: money(metrics.outstandingInvoices.amount), hint: `${metrics.outstandingInvoices.count} open invoice${metrics.outstandingInvoices.count === 1 ? '' : 's'}`, tone: 'danger' }]} />
            <div className="mb-6 grid gap-5 xl:grid-cols-3"><VristoTrendChart title="Platform growth" data={metrics.growthTrend} type="area" /><VristoTrendChart title="Revenue trend" data={metrics.revenueTrend} type="bar" currency /><VristoStatusChart data={metrics.subscriptionStatusDistribution} /></div>
            <div className="mb-6 grid gap-5 xl:grid-cols-3"><div className="panel xl:col-span-2 overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white-light p-5 dark:border-[#191e3a]"><div><h2 className="font-bold">Recent platform activity</h2><p className="text-sm text-white-dark">Subscription and administrative ledger events.</p></div><Link className="text-sm font-semibold text-primary" to="/superadmin/billing">Manage billing</Link></div>{metrics.recentTransactions.length ? <div className="overflow-x-auto"><table className="table-hover w-full"><thead><tr><th>Activity</th><th>Company</th><th>Status</th><th>Amount</th><th>Recorded</th></tr></thead><tbody>{metrics.recentTransactions.map((row) => <tr key={row.id}><td className="font-semibold">{humanize(row.transactionType)}</td><td><Link className="text-primary hover:underline" to={`/superadmin/companies/${row.company.id}`}>{row.company.name}</Link></td><td><StatusPill value={row.newStatus} /></td><td>{row.amount == null ? '—' : money(row.amount)}</td><td>{shortDate(row.createdAt)}</td></tr>)}</tbody></table></div> : <EmptyState title="No platform activity yet" description="Subscription and billing events will appear here." />}</div>
                <div className="panel"><h2 className="font-bold">System health</h2><p className="mb-5 text-sm text-white-dark">Core services requiring attention.</p><div className="space-y-4"><div className="flex items-center justify-between rounded bg-success-light p-3"><span className="font-semibold">Central database</span><span className="badge bg-success text-white">{humanize(metrics.systemHealth.database)}</span></div><div className={`rounded p-3 ${metrics.systemHealth.expiringSoon ? 'bg-warning-light' : 'bg-gray-50 dark:bg-dark'}`}><p className="font-semibold">Subscriptions expiring within 7 days</p><p className="mt-1 text-2xl font-black">{metrics.systemHealth.expiringSoon}</p><Link className="mt-2 inline-block text-sm font-semibold text-primary hover:underline" to="/superadmin/billing">Review subscriptions</Link></div></div></div></div>
            <div className="panel overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white-light p-5 dark:border-[#191e3a]"><div><h2 className="font-bold">Latest registrations</h2><p className="text-sm text-white-dark">Newest tenant organizations in the platform.</p></div><Link className="text-sm font-semibold text-primary" to="/superadmin/companies">View companies</Link></div>{metrics.latestRegistrations.length ? <div className="overflow-x-auto"><table className="table-hover w-full"><thead><tr><th>Company</th><th>Subdomain</th><th>Company status</th><th>Subscription</th><th>Registered</th><th /></tr></thead><tbody>{metrics.latestRegistrations.map((row) => <tr key={row.id}><td className="font-semibold">{row.name}</td><td>{row.subdomain}</td><td><StatusPill value={row.status} /></td><td><StatusPill value={row.subscriptionStatus} /></td><td>{shortDate(row.createdAt)}</td><td><Link className="btn btn-sm btn-outline-primary" to={`/superadmin/companies/${row.id}`}>Open</Link></td></tr>)}</tbody></table></div> : <EmptyState title="No companies registered" description="Onboard a company to begin managing the platform." action={<Link className="btn btn-primary" to="/superadmin/companies/new">Onboard company</Link>} />}</div>
        </>}
    </AppShell>;
};

const CompanyDashboard = () => {
    const [summary, setSummary] = useState<Record<string, unknown>>({}); const [error, setError] = useState('');
    useEffect(() => { api<Record<string, unknown>>('/api/dashboard/summary').then(setSummary).catch((reason) => setError(reason.message)); }, []);
    const metrics = Object.entries(summary).filter(([key, value]) => typeof value === 'number' && key !== 'profitMargin').slice(0, 8);
    return <AppShell><PageHeader eyebrow="Company overview" title="Executive hub" description="Live consolidated operational and financial indicators." />{error && <ErrorAlert message={error} />}{!Object.keys(summary).length && !error ? <div className="panel"><LoadingState /></div> : <StatGrid items={metrics.map(([label, value]) => ({ label: humanize(label), value: /income|expense|profit/i.test(label) ? money(value) : Number(value).toLocaleString(), tone: /expense/i.test(label) ? 'danger' : /income|profit/i.test(label) ? 'success' : 'primary' }))} />}</AppShell>;
};

const DashboardPage = ({ superAdmin = false }: { superAdmin?: boolean }) => superAdmin ? <PlatformDashboard /> : <CompanyDashboard />;
export default DashboardPage;
