import { FormEvent, useEffect, useState } from 'react';
import AppShell from '../components/maamulpro/AppShell';
import { EmptyState, ErrorAlert, Field, LoadingState, Modal, PageHeader, StatGrid, StatusPill, money } from '../components/maamulpro/PageKit';
import { api } from '../lib/api';

const featureOptions = [['construction', 'Construction workspace'], ['realEstate', 'Real estate workspace'], ['materials', 'Materials workspace'], ['payroll', 'Payroll'], ['advancedReports', 'Advanced reports'], ['prioritySupport', 'Priority support']] as const;
const initial = { key: '', name: '', description: '', priceMonthly: 0, priceYearly: 0, constructionMax: 0, propertiesMax: 0, usersMax: 5, isActive: true, features: {} as Record<string, boolean> };
const limitLabel = (value: number) => Number(value) === 0 ? '∞' : Number(value).toLocaleString();

const SubscriptionPlansPage = () => {
    const [rows, setRows] = useState<any[]>([]); const [form, setForm] = useState<any>(initial); const [editing, setEditing] = useState<any>(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
    const load = () => { setLoading(true); api<any[]>('/api/superadmin/plans').then(setRows).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }; useEffect(() => { load(); }, []);
    const edit = (row: any) => { setEditing(row); setForm({ ...initial, ...row, features: row.features || {} }); setOpen(true); };
    const submit = async (event: FormEvent) => { event.preventDefault(); try { await api(editing ? `/api/superadmin/plans/${editing.id}` : '/api/superadmin/plans', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(form) }); setOpen(false); setEditing(null); setForm(initial); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save plan'); } };
    return <AppShell><PageHeader eyebrow="Platform subscriptions" title="Subscription plans" description="Authoritative pricing, module access and capacity limits. Changes synchronize to active subscribers." actions={<button className="btn btn-primary" onClick={() => { setEditing(null); setForm(initial); setOpen(true); }}>New plan</button>} />
        <StatGrid items={[{ label: 'Plans', value: rows.length }, { label: 'Active plans', value: rows.filter((row) => row.isActive).length, tone: 'success' }, { label: 'Lowest monthly', value: money(rows.length ? Math.min(...rows.map((row) => Number(row.priceMonthly))) : 0), tone: 'info' }, { label: 'Highest user limit', value: rows.length ? Math.max(...rows.map((row) => Number(row.usersMax))) : 0, tone: 'warning' }]} />
        {error && <ErrorAlert message={error} onRetry={load} />}{loading ? <div className="panel"><LoadingState /></div> : !rows.length ? <div className="panel"><EmptyState title="No subscription plans" /></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows.map((row) => <article className="panel" key={row.id}><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-primary">{row.key}</p><h2 className="mt-1 text-xl font-bold">{row.name}</h2></div><StatusPill value={row.isActive ? 'ACTIVE' : 'INACTIVE'} /></div><p className="mt-3 min-h-[2.5rem] text-sm text-white-dark">{row.description || 'No description'}</p><p className="mt-5 text-3xl font-black">{money(row.priceMonthly)}<span className="text-sm font-normal text-white-dark"> / month</span></p><p className="text-sm text-white-dark">{money(row.priceYearly)} yearly</p><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded bg-gray-50 p-2 dark:bg-dark"><strong className="block text-base">{limitLabel(row.usersMax)}</strong>Users</div><div className="rounded bg-gray-50 p-2 dark:bg-dark"><strong className="block text-base">{limitLabel(row.constructionMax)}</strong>Projects</div><div className="rounded bg-gray-50 p-2 dark:bg-dark"><strong className="block text-base">{limitLabel(row.propertiesMax)}</strong>Properties</div></div><div className="mt-4 flex flex-wrap gap-1">{Object.entries(row.features || {}).filter(([, enabled]) => enabled).map(([key]) => <span className="badge bg-primary-light text-primary" key={key}>{key.replace(/([A-Z])/g, ' $1')}</span>)}</div><button className="btn btn-outline-primary mt-5 w-full" onClick={() => edit(row)}>Edit plan</button></article>)}</div>}
        <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit subscription plan' : 'New subscription plan'} wide><form className="grid gap-5 md:grid-cols-2" onSubmit={submit}>
            <Field label="Plan key" required hint="Permanent unique identifier"><input className="form-input mt-1" required disabled={Boolean(editing)} value={form.key} onChange={(e) => setForm({ ...form, key: e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, '') })} /></Field><Field label="Plan name" required><input className="form-input mt-1" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field>
            <Field label="Monthly price" required><input className="form-input mt-1" type="number" min="0" required value={form.priceMonthly} onChange={(e) => setForm({ ...form, priceMonthly: Number(e.target.value) })} /></Field><Field label="Yearly price" required><input className="form-input mt-1" type="number" min="0" required value={form.priceYearly} onChange={(e) => setForm({ ...form, priceYearly: Number(e.target.value) })} /></Field>
            <Field label="User limit" hint="Use 0 for unlimited"><input className="form-input mt-1" type="number" min="0" value={form.usersMax} onChange={(e) => setForm({ ...form, usersMax: Number(e.target.value) })} /></Field><Field label="Construction project limit" hint="Use 0 for unlimited"><input className="form-input mt-1" type="number" min="0" value={form.constructionMax} onChange={(e) => setForm({ ...form, constructionMax: Number(e.target.value) })} /></Field><Field label="Property limit" hint="Use 0 for unlimited"><input className="form-input mt-1" type="number" min="0" value={form.propertiesMax} onChange={(e) => setForm({ ...form, propertiesMax: Number(e.target.value) })} /></Field>
            <div className="md:col-span-2"><Field label="Description"><textarea className="form-textarea mt-1" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></div>
            <div className="md:col-span-2"><h3 className="font-bold">Included capabilities</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{featureOptions.map(([key, label]) => <label className="flex items-center gap-3 rounded border border-white-light p-3 dark:border-dark" key={key}><input className="form-checkbox" type="checkbox" checked={Boolean(form.features[key])} onChange={(e) => setForm({ ...form, features: { ...form.features, [key]: e.target.checked } })} />{label}</label>)}</div></div>
            <label className="flex items-center gap-3"><input className="form-checkbox" type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} />Active plan</label><div className="flex justify-end gap-2 md:col-span-2"><button type="button" className="btn btn-outline-dark" onClick={() => setOpen(false)}>Cancel</button><button className="btn btn-primary">Save plan</button></div>
        </form></Modal>
    </AppShell>;
};

export default SubscriptionPlansPage;
