import { FormEvent, useEffect, useState } from 'react';
import AppShell from '../components/maamulpro/AppShell';
import { ErrorAlert, Field, LoadingState, PageHeader, shortDate } from '../components/maamulpro/PageKit';
import { api, sessionStore } from '../lib/api';

const SuperAdminAccountPage = () => {
    const [account, setAccount] = useState<any>(null); const [email, setEmail] = useState({ email: '', currentPassword: '' }); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState('');
    const load = () => api<any>('/api/superadmin/account').then((row) => { setAccount(row); setEmail((current) => ({ ...current, email: row.email })); }).catch((reason) => setError(reason.message)); useEffect(() => { load(); }, []);
    const updateEmail = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { const row = await api<any>('/api/superadmin/account/email', { method: 'PATCH', body: JSON.stringify(email) }); const session = sessionStore.get(); if (session) sessionStore.set({ ...session, user: { ...session.user, email: row.email } }); setEmail({ email: row.email, currentPassword: '' }); setMessage('Email address updated.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Update failed'); } };
    const updatePassword = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); if (password.newPassword !== password.confirmPassword) { setError('Passwords do not match'); return; } try { await api('/api/superadmin/account/password', { method: 'PATCH', body: JSON.stringify({ currentPassword: password.currentPassword, newPassword: password.newPassword }) }); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); setMessage('Password updated successfully.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Update failed'); } };
    return <AppShell><PageHeader eyebrow="Platform security" title="Administrator account" description="Manage your platform sign-in identity and password." />{error && <ErrorAlert message={error} />}{message && <div className="mb-5 rounded-md bg-success-light p-4 text-success">{message}</div>}{!account ? <div className="panel"><LoadingState /></div> : <div className="grid gap-6 xl:grid-cols-2"><div className="panel" id="profile"><h2 className="text-lg font-bold">Account profile</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase text-white-dark">Name</dt><dd className="font-bold">{account.name}</dd></div><div><dt className="text-xs uppercase text-white-dark">Role</dt><dd className="font-bold">Super Admin</dd></div><div><dt className="text-xs uppercase text-white-dark">Created</dt><dd>{shortDate(account.createdAt)}</dd></div><div><dt className="text-xs uppercase text-white-dark">Last sign in</dt><dd>{shortDate(account.lastLoginAt)}</dd></div><div><dt className="text-xs uppercase text-white-dark">Password changed</dt><dd>{shortDate(account.passwordResetAt)}</dd></div></dl></div>
            <form className="panel space-y-4" id="settings" onSubmit={updateEmail}><h2 className="text-lg font-bold">Account settings</h2><Field label="New email" required><input className="form-input mt-1" type="email" required value={email.email} onChange={(e) => setEmail({ ...email, email: e.target.value })} /></Field><Field label="Current password" required><input className="form-input mt-1" type="password" required value={email.currentPassword} onChange={(e) => setEmail({ ...email, currentPassword: e.target.value })} /></Field><button className="btn btn-primary">Update email</button></form>
            <form className="panel space-y-4 xl:col-span-2" id="password" onSubmit={updatePassword}><h2 className="text-lg font-bold">Change password</h2><p className="text-sm text-white-dark">Use at least 10 characters with uppercase, number and special character.</p><div className="grid gap-4 md:grid-cols-3"><Field label="Current password" required><input className="form-input mt-1" type="password" required value={password.currentPassword} onChange={(e) => setPassword({ ...password, currentPassword: e.target.value })} /></Field><Field label="New password" required><input className="form-input mt-1" type="password" minLength={10} required value={password.newPassword} onChange={(e) => setPassword({ ...password, newPassword: e.target.value })} /></Field><Field label="Confirm password" required><input className="form-input mt-1" type="password" minLength={10} required value={password.confirmPassword} onChange={(e) => setPassword({ ...password, confirmPassword: e.target.value })} /></Field></div><button className="btn btn-primary">Update password</button></form></div>}
    </AppShell>;
};

export default SuperAdminAccountPage;
