import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import AppShell from '../components/maamulpro/AppShell';
import { EmptyState, ErrorAlert, LoadingState, PageHeader, StatGrid, StatusPill, money, shortDate } from '../components/maamulpro/PageKit';
import { api } from '../lib/api';

type Company = any;
type Response = { data: Company[]; meta: { page: number; pageSize: number; total: number; totalPages: number } };

const SuperAdminCompaniesPage = () => {
    const [result, setResult] = useState<Response | null>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
    const query = useMemo(() => new URLSearchParams({ page: String(page), pageSize: '20', ...(search.trim() ? { search: search.trim() } : {}), ...(status ? { status } : {}) }).toString(), [page, search, status]);
    const load = () => { setLoading(true); setError(''); api<Response>(`/api/superadmin/companies?${query}`).then(setResult).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); };
    useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [query]);
    const rows = result?.data || []; const meta = result?.meta;
    return <AppShell><PageHeader eyebrow="Platform administration" title="Companies" description="Tenant organizations, subscription state, workspace access and owner accounts." actions={<Link className="btn btn-primary" to="/superadmin/companies/new">Onboard company</Link>} />
        <StatGrid items={[{ label: 'Companies', value: meta?.total || 0 }, { label: 'Active on this page', value: rows.filter((row) => row.status === 'ACTIVE').length, tone: 'success' }, { label: 'Suspended on this page', value: rows.filter((row) => row.status === 'SUSPENDED').length, tone: 'danger' }, { label: 'Subscription value', value: money(rows.reduce((sum, row) => sum + Number(row.subscriptionAmount || 0), 0)), tone: 'info' }]} />
        <div className="panel mb-5 grid gap-3 md:grid-cols-[1fr_220px]"><input className="form-input" placeholder="Search company, subdomain or owner…" value={search} onChange={(e) => { setPage(1); setSearch(e.target.value); }} /><select className="form-select" value={status} onChange={(e) => { setPage(1); setStatus(e.target.value); }}><option value="">All company statuses</option>{['ACTIVE', 'SUSPENDED', 'PENDING_SETUP'].map((value) => <option key={value} value={value}>{value.replace(/_/g, ' ')}</option>)}</select></div>
        {error && <ErrorAlert message={error} onRetry={load} />}{loading ? <div className="panel"><LoadingState /></div> : !rows.length ? <div className="panel"><EmptyState title="No matching companies" description="Try a different filter or onboard a new company." action={<Link className="btn btn-primary" to="/superadmin/companies/new">Onboard company</Link>} /></div> : <div className="panel overflow-hidden p-0"><div className="overflow-x-auto"><table className="table-hover w-full"><thead><tr><th>Company</th><th>Owner</th><th>Plan</th><th>Users</th><th>Workspaces</th><th>Expires</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.name}</strong><p className="text-xs text-white-dark">{row.subdomain}</p></td><td>{row.adminName}<p className="text-xs text-white-dark">{row.adminEmail}</p></td><td>{row.currentSubscription?.plan?.name || row.planKey || row.planTier || 'Unassigned'}</td><td>{row._count?.users || 0}</td><td><div className="flex gap-1">{row.constructionEnabled && <span className="badge bg-primary-light text-primary">Construction</span>}{row.realEstateEnabled && <span className="badge bg-info-light text-info">Real estate</span>}{row.materialManagementEnabled && <span className="badge bg-warning-light text-warning">Materials</span>}</div></td><td>{shortDate(row.subscriptionExpiresAt)}</td><td><StatusPill value={row.subscriptionStatus} /></td><td><Link className="btn btn-sm btn-outline-primary" to={`/superadmin/companies/${row.id}`}>Manage</Link></td></tr>)}</tbody></table></div>{meta && <div className="flex items-center justify-between border-t border-white-light px-5 py-4 text-sm dark:border-[#191e3a]"><span className="text-white-dark">Page {meta.page} of {meta.totalPages} · {meta.total} companies</span><div className="flex gap-2"><button className="btn btn-sm btn-outline-primary" disabled={meta.page <= 1} onClick={() => setPage(meta.page - 1)}>Previous</button><button className="btn btn-sm btn-outline-primary" disabled={meta.page >= meta.totalPages} onClick={() => setPage(meta.page + 1)}>Next</button></div></div>}</div>}
    </AppShell>;
};

export default SuperAdminCompaniesPage;
